### ISSUE TITLE
Meta data for different actions on items

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#1]
_From @willwade on May 22, 2017 11:30_

When a user selects the end of the branch it should speak it.

- It should return to the top of the tree by default
- IF However the item has a star in brackets after it then stay on that level.. e.g.

```
## I shall spell it

### a (*)

### b (*)

### c (*)
```

(so spelling it would be possible)

NOTE: IGNORE READING OUT ITEMS IN BRACKETS ;) 

NOTE 2: There could be a better way of formatting this text to denote this. Any other better ideas welcome! (Maybe this is how we link to recorded audio files too. E.g. (`## I shall spell it (f:somefile.mp3)`)

_Copied from original issue: hosseinamin/audscan#1_

**Comment by willwade** [comment]
1 hr

**Comment by willwade** [comment]
_From @hosseinamin on June 4, 2017 2:33_

The better way to add these info is as follows.

```
## I shall spell it<meta data-onselect-restart-here>
```

**Comment by willwade** [comment]
I'm thinking there needs to be a range of meta -data that can be read. For example..

- Short auditory cue (when it rapidly moves through the list initially) 
- Longer auditory cue (when it moves through slowly)
- on-select-restart-here

how about 
`## I shall spell it (restart-here, cue-short:spell, cue-long:spell it)`

**Comment by willwade** [comment]
_From @hosseinamin on June 6, 2017 11:27_

That's possible with meta tag. It's integrated with html. easy to implement and standard.
Here's an example.
```
## I shall spell it<meta data-onselect-restart-here data-cue-short="spell" data-cue-long="spell it">
```

**Comment by hosseamin** [comment]
Done

**Comment by hosseinamin** [comment]
Done
