### ISSUE TITLE
UI: A way of text being enlarged

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#10]
Text should be scalable in size.. 
- Either it should use iOS in-built dynamic text sizing..

- Or failing that a way in-app to increase font size. Note really the main highlighted item is the key one to increase in size..

**Comment by willwade** [comment]
May require https://github.com/phonegap/phonegap-mobile-accessibility (as read here: https://stackoverflow.com/questions/28848132/phonegap-how-control-the-font-size-of-the-mobile#28943502)

**Comment by hosseinamin** [comment]
@willwade i did try mobile accessibility plugin. It doesn't do text zoom well. It's best for us to control it in the app.
However we can get preferred text zoom in percentage and decide how to scale text.

**Comment by hosseinamin** [comment]
I don't think it's important to use preferred text zoom. How about we just have an option for it at configure?

**Comment by hosseinamin** [comment]
This commit supports determining column width based on its level and content size given.
also it implements enlarging font-size.
Another upgrade is to enable tree files to set custom class on specific node on the hierarchy. So it can get selected with css. Actually this is simple a meta can do it. like `data-class`

**Comment by willwade** [comment]
closing for now.
