### ISSUE TITLE
UI: Change colours/theme

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#11]
- We should have an option to turn on a high-contrast colour theme
(e.g. using a pallete like Yellow text on Black background) - along with the current view. 

Either:
- Choose your own colours (not great though - people make it look a mess)
- Have an option for "High contrast theme". (e.g. https://color.adobe.com/High-contrast-color-theme-349965/)
- Or provide a range of pre-selected colour themes with high-contrast being one of them.

**Comment by hosseinamin** [comment]
This is the first suggestion from me. Please take a look. 
Two themes are there. Light and Dark

**Comment by willwade** [comment]
Awesome. Closing this. Done.
