### ISSUE TITLE
Rapid- Pre-Auditory Cue scan

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#13]
For some people who are blind they can hear a short cue relatively quickly first. So we would like an option available in the configuration for "Initial rapid auditory cue" - so the first run of any tree is fast - and speed should be configurable. 

I guess this is a fast auditory cue speed for first run through. Second and onwards of that tree should be normal speed.

**Comment by willwade** [comment]
Think there is a small bug with current build. There is no default rate or pitch so all configuration fails to save. 

Can we have a on/off toggle radio button  - with pressing on displaying the rapid scan cue settings?

**Comment by willwade** [comment]
One other thing. Just realised this option should only be available if auto-scanning is on. Sorry to be a pain!

**Comment by hosseinamin** [comment]
> One other thing. Just realised this option should only be available if auto-scanning is on. Sorry to be a pain!

It's only available for auto mode. No problem.

> Can we have a on/off toggle radio button - with pressing on displaying the rapid scan cue settings?

OK

> Think there is a small bug with current build. There is no default rate or pitch so all configuration fails to save.

This is because the old config was saved at on app. quick solution is...

```
A new feature is added for debugging at main page. When hardware keyboard is on or navigation buttons is off.
Pressing on . (dot) will turn debug mode on.
In menu next to configure button you will see Clear storage. 
This button will delete saved tree/config files.
```

**Comment by willwade** [comment]
cool. I think that one is fixed then.. Certainly not seeing the problem now.

**Comment by willwade** [comment]
One more.. we have a problem where the voice isn't saving.. 

https://www.dropbox.com/s/fv3999qoany5egg/AudCueNotSaving.mov?dl=0

**Comment by hosseinamin** [comment]
@willwade Fixed

**Comment by willwade** [comment]
That was quick! Ok one more. This only appears in Safari - if a big problem we can force people to Chrome but if fixable.. 

So a couple of things. I *think* the space or enter isn't being saved. Also there is a weird bug that runs through the items really quickly - this is ignoring the rapidscan feature. 

https://www.dropbox.com/s/cslprnm6do8dx5m/WierdSpeedBugSafari.mov?dl=0

**Comment by hosseinamin** [comment]
>That was quick! Ok one more. This only appears in Safari - if a big problem we can force people to Chrome but if fixable..

@willwade That has something to do with responsiveVoice service. I will check it in details.

**Comment by willwade** [comment]
Is this the same thing? (In firefox) https://www.dropbox.com/s/7u2rxhrehqyzy4o/WierdSpeedBugSafari2.mov?dl=0

**Comment by hosseinamin** [comment]
new chrome and firefox did provide native support for speech synthesis. 

https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

Here's a demo,
http://mdn.github.io/web-speech-api/speak-easy-synthesis/

**Comment by hosseinamin** [comment]
`responsiveVoice` did plan to use those native api. But It's not mentioned in their API page. I think it's not fully implemented yet.

**Comment by hosseinamin** [comment]
@willwade I hope the weird speed issue is fixed. Please test it

**Comment by willwade** [comment]
Great. Looking good so far. Thanks - know it wasn't easy

**Comment by hosseinamin** [comment]
It was an easy fix :)

Did take some time to solve some other issues close to it.
