### ISSUE TITLE
Editor. 

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#15]
What are the best ways to edit the markdown for the non-technical person?

I have some ideas..

1. Either a cut-down in place editor that only has H1 fields and bullet points (e.g. Like this but with only h1, h2, h3, h4 and # https://github.com/jaredreich/pell/blob/master/README.md)
2. Something like this: http://gojs.net/latest/samples/mindMap.html * (see pic)

<img width="512" alt="screen shot 2017-07-10 at 17 02 47" src="https://user-images.githubusercontent.com/229352/28027633-a6defd92-6591-11e7-99bf-c73fbb689358.png">

What were you thinking @hosseinamin ?

Note: We DO want the markdown format the main format - I'm not suggesting changing that!!

* See also https://github.com/dundalek/markmap

**Comment by willwade** [comment]
(Nb re: idea 1. Like this but with only h1, h2, h3, h4 and # https://github.com/jaredreich/pell/blob/master/README.md)

**Comment by hosseinamin** [comment]
> Either a cut-down in place editor that only has H1 fields and bullet points (e.g. Like this but with only h1, h2, h3, h4 and # https://github.com/jaredreich/pell/blob/master/README.md)

This is possible but not necessary. i think `#` rule is very simple already

> Something like this: http://gojs.net/latest/samples/mindMap.html * (see pic)

The editor seems to not have necessary editing features. like add bellow or above, also re-ordering.


I do suggest having a custom editor. actually the current running app is good for it. UI part is half ready. It just needs few buttons. (add bellow/above, add child) and select feature.
For metadata (in future) we can have a sidebar containing all metadata of selected item, and ability to add/edit/delete...

**Comment by willwade** [comment]
Ah ok. Yes. That makes sense.  Would it save it as markdown still?

**Comment by hosseinamin** [comment]
> Would it save it as markdown still?

yes

**Comment by hosseinamin** [comment]
EE: 4-6H

**Comment by hosseinamin** [comment]
Implemented

**Comment by willwade** [comment]
That's awesome. Nice job!

**Comment by hosseinamin** [comment]
Good to know. I did few tests on it. If it's okay you can close the issue

**Comment by willwade** [comment]
One minor thing. How do you navigate to a child node rather than add when in edit?

**Comment by hosseinamin** [comment]
Navigation will work as before. When input text is focused (so we can change it). By hitting enter or escape it will blur and you can navigation with arrows or enter/space.
The edit mode does work like switch mode for navigation.

**Comment by willwade** [comment]
Great!
