### ISSUE TITLE
Support recorded (mp4 or .wav) files for cue and main audio

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#16]
This is a bit tricky. 
Ideally we want to be able to support recorded speech files for both the main speech and audio. 

Suggested ways of working:

- In config pass in a  URL of a root path (e.g. dropbox folder that is publicly shared) 
- Then app will look for files named the same as the message e.g " - People " (look for dropbox_path+"people.wav|mp4" etc). Or use the metadata function meta-data recorded-audio:file.mp4
- Download these and cache them ALL locally on initial run

- For cue files - use the volume provided by the cue voice. 
- For main audio - use the volume provided by the main voice

**Comment by hosseinamin** [comment]
It needs some refinements.

1. Assuming user wants to edit it then input does not need to be on the internet. It can be on internet, but it will get downloaded/saved immediately.
2. If it comes from a tree file. then assuming that tree file is on internet. then with downloading and saving the tree file, downloading all audio files with it is appropriate.

So i think in most cases having a relative path for referenced files is good enough.

**Comment by hosseinamin** [comment]
Partial Implementation,

1. Support for audio playback as utterance

EE: 1-3H

```
FOR_LATER, TODO::
1. Download external tree files. As import function (currently I'm thinking of ajax calls)
2. manage downloaded tree files. to remove unused tree files. 
     and selection of available tree files in config. 
```

**Comment by hosseinamin** [comment]
Implemented

**Comment by willwade** [comment]
Great. Can you just explain how to demo this?

**Comment by hosseinamin** [comment]
I've already did put a test sample in there. You can clear storage to see it.

https://github.com/willwade/pasco/commit/54eb6a67fd7702b16ea1ab12f15d2ee174c781d0#diff-50ca8c30612c70adbab9807f44b6065fR474

https://github.com/willwade/pasco/tree/master/html/test-assets

Currently it does not work on iOS. I need to implement an alternative version to make it work there. with cordova-plugin-media

**Comment by willwade** [comment]
Great. So how do you do a different cue audio file to a main audio file? Is that possible?

**Comment by hosseinamin** [comment]
Yes

**Comment by hosseinamin** [comment]
Now it works as follows.
```
to play recorded audio look for these meta tags in order, if found use it otherwise speak the text

CUE => data-cue-audio or data-audio
MAIN => data-main-audio or data-audio
```

**Comment by willwade** [comment]
Great. Thanks!

**Comment by willwade** [comment]
Just leaving this open for now - its done - just so we do the next part (FOR_LATER, TODO)
