### ISSUE TITLE
Need credits and help link

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#17]
Need some way of adding in a credits screen (Notably where we state that we are using responsive voice as part of their EULA). 

May also be wise to link off to a help link (just to https://pasco.chat/#help )

Not urgent - but probably a good idea before submitting app.

**Comment by hosseinamin** [comment]
EE: 1-2H

**Comment by hosseinamin** [comment]
Done, Needs some changes...

**Comment by willwade** [comment]
Cool. Sorry to be a pain but maybe we should put credits in a help page. And have a short in-app help text. 

I.e.  Remove help link, make credits page the help page. ! What a pain I am!

**Comment by hosseinamin** [comment]
I don't think i understand.  can you elaborate?

The content of credits page are temporary. I didn't know what to put in them.

**Comment by hosseinamin** [comment]
Ah. So in links i remove credits. and help page will be within app contains credits as well...

**Comment by willwade** [comment]
You got it!

So credits -> help
Remove old help link. 

I'll then populate new help page. :)
