### ISSUE TITLE
No speech on web iOS (safari / chrome)

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#18]
It's not major - the main port we need to focus on is the iOS app - but I'm not getting any speech output on iOS web - either chrome or safari

**Comment by hosseinamin** [comment]
@willwade In edit mode i did disable audio. Is it related to that?

**Comment by willwade** [comment]
No. Not in edit mode. Is it working fine on desktop? Haven't had a chance
to test. I'm wondering if it's a cache thing.

**Comment by hosseinamin** [comment]
Now i understand. I did not payed enough attention at title. Okay. I'll check...

**Comment by hosseinamin** [comment]
Got it. Because of some security reason iOS did prevent two things here. 

1. Auto play of audio (with no button to click) 
2. Auto focus keyboard

I might need to use this plugin to get #16 to work on iOS.
https://github.com/eiffelqiu/phonegap-videoplayer-plugin

**Comment by willwade** [comment]
Now working. NB: Turn rapid auditory cue off and it speaks.. WIERD!

**Comment by hosseinamin** [comment]
Apparently responsiveVoice in Mac OSX is using native Speech Synthesizer.
I'm not sure what's wrong. I'll get into this later.

**Comment by willwade** [comment]
I'm closing this. No idea what went wrong but its apparently working
