### ISSUE TITLE
Controls (arrow keys) not working in firefox  or Safari (MacOS)

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#20]
Again - low priority - but strangely these aren't working in Firefox or Safari on MacOS.

Odd

**Comment by willwade** [comment]
Strange. When I set "first Time run" voice off it works. When on it doesn't.

**Comment by willwade** [comment]
closing. weird. seems to not be a problem anymore

**Comment by hosseinamin** [comment]
Great
