### ISSUE TITLE
Small visual bug in chrome

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#21]
Just running it as is in Chrome there is a bug with the appearance not clearing out when you go back...

Otherwise great! 
<img width="937" alt="screen shot 2017-07-24 at 21 20 05" src="https://user-images.githubusercontent.com/229352/28542956-14cc5014-70b6-11e7-8ef5-15af121ff8fd.png">

**Comment by hosseinamin** [comment]
Fixed.
