### ISSUE TITLE
UI: Config

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#7]
_From @willwade on June 19, 2017 9:19_

Under Mode:
2 Options currently (3 if we ever do #5)
- "Auto-Scanning"
- "Manual-Scanning" 

(a Question. If "Manual scanning" (currently "Switch") - are there keys also for navigating back stepping forward and selecting? Should we not be showing those too?)

_Copied from original issue: hosseinamin/audscan#8_

**Comment by hosseamin** [comment]
@willwade 
> (a Question. If "Manual scanning" (currently "Switch") - are there keys also for navigating back stepping forward and selecting? Should we not be showing those too?)

Yes. We need more options in there. I just couldn't find the right option name to use...

**Comment by willwade** [comment]
New bits.. 

1. Move “Switch Access” section below “Mode”.

2. Mode - rename “Switch Access”. rename “Auto” to “Manual”. Then when “Manual” shown just have some text to describe what key presses the app is looking for. (Numbers right?).

**Comment by willwade** [comment]
closing. think all done for now.
