### ISSUE TITLE
Meta-data for Auditory Cue (and in brackets)

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#8]
Need a simple - and more complex way of having a different auditory cue..

- So simple method: Text in brackets after each item e.g. "I want to go somewhere (go somewhere)"
- Advanced method: Meta tag e.g. <meta auditory-cue:"some string here">

**Comment by hosseinamin** [comment]
Instead of colon separator be equal to work as html. or i can design a custom parser for that. @willwade which one do you prefer?

> Advanced method: Meta tag e.g. <meta auditory-cue:"some string here">

**Comment by willwade** [comment]
Sorry. Not understanding. Do you mean it's either:
Long phrase : short cue 
Or
Long phrase (short cue) 

First method easier - second would require more work?

**Comment by hosseinamin** [comment]
First one is ok.

> So simple method: Text in brackets after each item e.g. "I want to go somewhere (go somewhere)"

Second one better to be in html format.

> Advanced method: Meta tag e.g. <meta auditory-cue="some string here">

**Comment by willwade** [comment]
Possible to do both?

**Comment by willwade** [comment]
I can see the meta method better as it's consistent for the other features. But initially we want to make it super easy for non-technical people to edit. So I vote for the simpler method - if not very difficult! But ideally both methods would work (and in the scenario where a meta tag exists and there is text in brackets the meta tag would take precedence)

**Comment by hosseinamin** [comment]
> Possible to do both?

yes. I prefer the second one to be in html format.

**Comment by willwade** [comment]
Ok. Fine with me for second one to be HTML format

**Comment by hosseinamin** [comment]
It's unsafe to do other methods. other that html.

Since markdown content will get converted to html with its own formatting. Like having two stars in it which makes bold.

**Comment by hosseinamin** [comment]
Anyway we can try. Not hard to do

**Comment by hosseinamin** [comment]
@willwade It should be working now.
example is in the commit 
https://github.com/willwade/pasco/commit/6e213db1123c957277012ec3d2cabe05b5975a63#diff-50ca8c30612c70adbab9807f44b6065fR238
