### ISSUE TITLE
Make on-screen navigation slightly lighter

### ISSUE THREAD

**Issue by willwade** [willwade/pasco#9]
The black surround of the on-screen navigation (arrows) is a little to clear. The current highlighted text should be the clearest thing on-screen. 

Propose just making the outline lighter.

**Comment by hosseinamin** [comment]
@willwade Please check...
You can modify it at here
https://github.com/willwade/pasco/commit/6e213db1123c957277012ec3d2cabe05b5975a63#diff-481aabc2c4b6bc847de06caf0e2b5200R159
